---
grpc:
  server:
    port: ${GRPC_SERVER_PORT:55593}

security:
  basic:
    enabled: false
region:
  prefecture: files/region-prefecture.xlsx

industryType:
  mrjobtype: files/mrjobtype.xlsx


#Config db
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password:

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

